version: '3.1'
services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
    - '3309:3306'
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    volumes:
    - mysqlV:/var/lib/mysql
    networks:
      - mysql_adminer

  adminer:
    container_name: adminer_watcher
    hostname: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mysql_adminer

volumes:
  mysqlV:

networks:
  mysql_adminer:
    driver: bridge
